POST http://localhost:80/api/holding
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

{
    "portfolio_id": 2,
    "symbol": "ANKR",
    "expected_sell": 25
}

###
GET http://localhost:80/api/holding
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
GET http://localhost:80/api/holding/4
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
GET http://localhost:80/api/holding/portfolio/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json
