POST http://localhost:80/api/portfolio
Content-Type: application/json
Authorization: Bearer 10|597lulobSm1xrq57e7yyfYn55ASIshKOMatgTPHj
Accept: application/json

{
    "name": "test another user"
}

###
GET http://localhost:80/api/portfolio/2
Content-Type: application/json
Authorization: Bearer 10|597lulobSm1xrq57e7yyfYn55ASIshKOMatgTPHj
Accept: application/json

###
GET http://localhost:80/api/portfolio/user
Content-Type: application/json
Authorization: Bearer 10|597lulobSm1xrq57e7yyfYn55ASIshKOMatgTPHj
Accept: application/json

###
PUT http://localhost:80/api/portfolio
Content-Type: application/json
Authorization: Bearer 10|597lulobSm1xrq57e7yyfYn55ASIshKOMatgTPHj
Accept: application/json

{
    "id": 2,
    "name": "updated name2"
}
