POST http://localhost:80/api/portfolio
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

{
    "name": "Test User 2",
    "exchange": {
        "name": "Binance"
    }
}

###
GET http://localhost:80/api/portfolio/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
GET http://localhost:80/api/portfolio
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
PUT http://localhost:80/api/portfolio
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

{
    "id": 2,
    "name": "updated name2"
}

###
GET http://localhost:80/api/portfolio/1/summary
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json
