POST http://localhost:80/api/position
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

{
    "token_id": 5,
    "portfolio_id": 1,
    "status": "open"
}

###
DELETE http://localhost:80/api/position/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
GET http://localhost:80/api/position
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
GET http://localhost:80/api/position/7
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
GET http://localhost:80/api/position/1/orders
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
POST http://localhost:80/api/position/2/order
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

{
    "quantity": 499.2,
    "date": "2021-10-31 09:57",
    "status": "filled",
    "type": "buy"
}

###
GET http://localhost:80/api/position/1/order/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
GET http://localhost:80/api/position/1/order/1/prices
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
POST http://localhost:80/api/position/1/order/1/price
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

{
    "pair_id": 1,
    "price": 0.00003224
}

###
POST http://localhost:80/api/position/1/order/1/price
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

{
    "pair_id": 2,
    "price": 2.015
}



###
POST http://localhost:80/api/position
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

//< ./bodies/positionADA.json
//< ./bodies/positionBTC.json
//< ./bodies/positionBTT.json
//< ./bodies/positionDOT.json
//< ./bodies/positionEOS.json
//< ./bodies/positionICP.json
//< ./bodies/positionIOTA.json
//< ./bodies/positionMIR.json
//< ./bodies/positionSHIB.json
//< ./bodies/positionXTZ.json
//< ./bodies/positionYFI.json
< ./bodies/positionZIL.json

###
GET http://localhost:80/api/position/6/summary
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
GET http://localhost:80/api/position/1/summary/string
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json
