POST http://localhost:80/api/token
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

{
    "name": "ICP"
}

###
PUT http://localhost:80/api/token/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

{
    "name": "USDT"
}

###
GET http://localhost:80/api/token/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
GET http://localhost:80/api/token
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
POST http://localhost:80/api/token/5/pair/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
POST http://localhost:80/api/token/5/pair/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
GET http://localhost:80/api/token/4/pair/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
GET http://localhost:80/api/token/4/pairs
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json

###
GET http://localhost:80/api/token/1/pairs/as-quote
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Accept: application/json
