POST http://127.0.0.1/api/sanctum/token
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: application/json

--WebAppBoundary
Content-Disposition: form-data; name="email"

luke@jedi.com

--WebAppBoundary
Content-Disposition: form-data; name="password"

password
--WebAppBoundary
Content-Disposition: form-data; name="device_name"

postman
--WebAppBoundary--
